name: ScreenShot

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "37 */3 * * *"

jobs:
  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 2
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Deps
      run: |
        npm i yarn --location=global
        rm -rf package*.json
        yarn add chalk ora yarn puppeteer

    - name: Add Chinese Support # 添加中文语言支持
      run: |
        git remote -v  # 查看信息
        git pull origin master
        sudo apt-get install language-pack-zh-han*
        sudo apt-get install ttf-mscorefonts-installer
        sudo apt-get install fontconfig
        LANG="zh_CN.UTF-8"
        locale
        echo $LANG
        fc-list :lang=zh
        cp HarmonyOS.ttf /usr/share/fonts/
        sudo chmod 644 /usr/share/fonts/HarmonyOS.ttf
        sudo mkfontscale
        sudo mkfontdir
        sudo fc-cache -fv
        rm -rf fonts.*
    
    - name: Capture Screenshot
      id: screenshot
      run: |
        rm -rf snap/*.png pdf/*.pdf # 删除旧的
        node index.js
        # 刷新站点缓存
        curl https://purge.jsdelivr.net/gh/xiaozhu2007/ScreenShot@master/snap/baidu-top.png
        curl https://purge.jsdelivr.net/gh/xiaozhu2007/ScreenShot@master/snap/baidu.com.png
    - name: Prettier check
      uses: actionsx/prettier@v2
      with:
        args: --write .
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'docs: Update ScreenShots [skip ci]'
        branch: master
        commit_user_name: AGDDoS-bot
        commit_user_email: 3356136957@qq.com
        commit_author: AGDDoS-bot <3356136957@qq.com>
