name: ScreenShot

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "56 */8 * * *"

jobs:
  screenshot:
    name: Screenshot
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci

    - name: Add Chinese Support # 添加中文语言支持
      run: |
        git pull
        sudo apt-get install language-pack-zh-han*
        sudo apt-get install ttf-mscorefonts-installer
        sudo apt-get install fontconfig
        LANG="zh_CN.UTF-8"
        locale
        echo $LANG
        fc-list :lang=zh
        cp HarmonyOS.ttf /usr/share/fonts/
        sudo chmod 644 /usr/share/fonts/HarmonyOS.ttf
        sudo mkfontscale
        sudo mkfontdir
        sudo fc-cache -fv
    
    - name: Capture Screenshot
      id: screenshot
      run: |
        node index.js
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'docs: Update ScreenShots [skip ci]'
        branch: master
        commit_user_name: AGDDoS-bot
        commit_user_email: 3356136957@qq.com
        commit_author: AGDDoS-bot <3356136957@qq.com>
